import { FormEvent, useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import "./styles.css";

const API = `${(import.meta.env.VITE_API_URL || "").replace(/\/$/, "")}/api/v1`;
const tabs = ["Dashboard","Markets","Strategies","Backtesting","Signals","Orders","Positions","Trades","Portfolio","Risk","Broker","Logs","Settings"];
const symbols: Record<string,string> = { NIFTY:"NSE:NIFTY 50", BANKNIFTY:"NSE:NIFTY BANK", FINNIFTY:"NSE:NIFTY FIN SERVICE" };

async function api(path: string, init: RequestInit = {}) {
  const token = localStorage.getItem("autobot_token");
  const headers = new Headers(init.headers);
  if (token) headers.set("Authorization", `Bearer ${token}`);
  if (init.body && !headers.has("Content-Type")) headers.set("Content-Type", "application/json");
  const r = await fetch(API + path, { ...init, headers });
  if (r.status === 401) localStorage.removeItem("autobot_token");
  if (!r.ok) throw new Error(await r.text());
  return r.status === 204 ? null : r.json();
}
function Table({ rows }: { rows:any[] }) { if (!rows?.length) return <p className="muted">No records yet.</p>; const cols=Object.keys(rows[0]); return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{String(r[c] ?? "—")}</td>)}</tr>)}</tbody></table></div>; }

export default function App(){
 const [token,setToken]=useState(()=>localStorage.getItem("autobot_token"));
 const [tab,setTab]=useState("Dashboard"); const [underlying,setUnderlying]=useState("NIFTY");
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [showPassword,setShowPassword]=useState(false); const [loggingIn,setLoggingIn]=useState(false); const [error,setError]=useState("");
 const [fromDate,setFromDate]=useState(""); const [toDate,setToDate]=useState(""); const [mode,setMode]=useState("ATM"); const [selected,setSelected]=useState<string[]>([]); const [result,setResult]=useState<any>(null); const [events,setEvents]=useState<any[]>([]); const enabled=!!token;
 const broker=useQuery({queryKey:["broker"],queryFn:()=>api("/broker/status"),enabled}); const connected=broker.data?.status==="CONNECTED";
 const summary=useQuery({queryKey:["summary"],queryFn:()=>api("/dashboard/summary"),enabled,refetchInterval:10000});
 const chain=useQuery({queryKey:["chain",underlying],queryFn:()=>api(`/broker/zerodha/option-chain?underlying=${underlying}`),enabled:enabled&&connected&&tab==="Markets",refetchInterval:10000});
 const contracts=useQuery({queryKey:["contracts",underlying],queryFn:()=>api(`/broker/zerodha/options?underlying=${underlying}`),enabled:enabled&&connected&&tab==="Backtesting",staleTime:300000});
 const strategies=useQuery({queryKey:["strategies"],queryFn:()=>api("/strategies"),enabled}); const orders=useQuery({queryKey:["orders"],queryFn:()=>api("/orders"),enabled}); const positions=useQuery({queryKey:["positions"],queryFn:()=>api("/positions"),enabled}); const trades=useQuery({queryKey:["trades"],queryFn:()=>api("/trades"),enabled});
 useEffect(()=>{ if(!token) return; const backend=(import.meta.env.VITE_API_URL||location.origin).replace(/\/$/,""); const wsBase=backend.replace(/^http:/,"ws:").replace(/^https:/,"wss:"); const ws=new WebSocket(`${wsBase}/api/v1/ws/events?token=${encodeURIComponent(token)}`); ws.onmessage=e=>{try{const d=JSON.parse(e.data); if(d.type!=="heartbeat") setEvents(x=>[d,...x].slice(0,40));}catch{}}; return()=>ws.close(); },[token]);
 async function login(e:FormEvent){e.preventDefault();setError("");setLoggingIn(true);try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({email:email.trim(),password})});localStorage.setItem("autobot_token",d.access_token);setToken(d.access_token);}catch(err:any){setError("Invalid email or password");}finally{setLoggingIn(false);}}
 async function logout(){try{await api("/broker/zerodha/logout",{method:"POST"});}finally{localStorage.removeItem("autobot_token");setToken(null);}}
 async function connect(){const d=await api("/broker/zerodha/login");location.assign(d.login_url);}
 async function backtest(e:FormEvent){e.preventDefault();setError(""); if(mode==="MANUAL"&&!selected.length){setError("Select at least one option contract");return;} const qs=new URLSearchParams({from_date:fromDate,to_date:toDate,underlying,selection_mode:mode}); if(mode==="MANUAL"){const rows=(contracts.data??[]).filter((c:any)=>selected.includes(String(c.instrument_token)));qs.set("option_instrument_tokens",rows.map((x:any)=>x.instrument_token).join(","));qs.set("option_tradingsymbols",rows.map((x:any)=>x.tradingsymbol).join(","));} try{const d=await api(`/backtests/run/zerodha?${qs}`,{method:"POST"});setResult(d);}catch(err:any){setError(err.message||"Backtest failed");}}
 if(!token)return <main className="login-page"><div className="login-shell"><div className="login-brand"><span className="login-mark">◈</span><div><strong>AUTO BOT</strong><small>ALGORITHMIC TRADING TERMINAL</small></div></div><form className="login-card" onSubmit={login}><div><p className="login-kicker">WELCOME BACK</p><h1>Sign in to your workspace</h1><p className="login-subtitle">Secure access to your paper-trading command centre.</p></div><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com" required /></label><label>Password<div className="password-field"><input type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" placeholder="Enter your password" required /><button type="button" className="password-toggle" onClick={()=>setShowPassword(v=>!v)}>{showPassword?"Hide":"Show"}</button></div></label>{error&&<p className="error login-error">{error}</p>}<button className="login-submit" disabled={loggingIn}>{loggingIn?<><span className="spinner"/> Signing in…</>:"Sign in securely"}</button><div className="login-footer"><span><i/> PAPER MODE</span><span>Encrypted session</span></div></form><p className="login-disclaimer">Trading access is protected by your account permissions. Paper mode never places real broker orders.</p></div></main>;
 const selector=<select value={underlying} onChange={e=>{setUnderlying(e.target.value);setSelected([])}}>{Object.keys(symbols).map(x=><option key={x}>{x}</option>)}</select>;
 let page:any=<section className="panel"><h3>{tab}</h3><p className="muted">Select a workspace from the navigation.</p></section>;
 if(tab==="Dashboard") page=<><section className="hero"><div><p className="live-label"><i/> REAL-TIME PAPER TRADING</p><h3>Trading command centre</h3><p>Tick-driven market data, strategy events and paper P&amp;L in one terminal.</p></div><div className="hero-orb">PAPER<br/>LIVE</div></section><section className="cards dashboard-cards">{[["Signals",summary.data?.bot_calls??0,"signals"],["Winning trades",summary.data?.successful_trades??0,"positive"],["Losing trades",summary.data?.failed_trades??0,"negative"],["Win rate",`${summary.data?.win_rate??0}%`,"rate"],["Net P&L",`₹${summary.data?.net_pnl??0}`,"pnl"],["Open positions",summary.data?.open_positions??0,"positions"]].map(([a,b,c])=><div className={`card metric ${c}`} key={String(a)}><small>{a}</small><strong>{b}</strong><span>Live account state</span></div>)}</section><section className="grid"><div className="panel"><div className="panel-title"><h3>Event stream</h3><span className="live-badge">LIVE</span></div>{events.length?<div className="event-list">{events.slice(0,8).map((e,i)=><div className="event" key={i}><b>{e.type}</b><span>{e.underlying||e.event||"System"}</span><time>{e.ts?new Date(e.ts).toLocaleTimeString():"now"}</time></div>)}</div>:<p className="muted">Waiting for real-time events from Redis.</p>}</div><div className="panel"><h3>Connection health</h3><div className="health-row"><span className="status-dot"/> Kite <b>{broker.data?.status??"CHECKING"}</b></div><div className="health-row"><span className="status-dot"/> WebSocket <b>{events.length?"RECEIVING":"WAITING"}</b></div><div className="health-row"><span className="status-dot"/> Mode <b>PAPER</b></div></div></section></>;
 if(tab==="Markets") page=<section className="panel market-panel"><div className="page-heading"><div><p className="live-label"><i/> LIVE TICKS</p><h3>Option chain</h3><p className="muted">Quotes are displayed from Kite; trading events arrive through WebSocket.</p></div>{selector}</div>{!connected?<p>Connect Kite from Broker to view data.</p>:chain.isLoading?<p>Loading…</p>:chain.error?<p className="error">Could not load live option data.</p>:<><section className="cards market-cards"><div className="card"><small>{underlying} Spot</small><strong>₹{chain.data.spot}</strong></div><div className="card"><small>ATM</small><strong>{chain.data.atm_strike}</strong></div><div className="card"><small>Expiry</small><strong>{chain.data.expiry}</strong></div></section><div className="table-wrap"><table className="option-chain"><thead><tr><th>Call LTP</th><th>Call OI</th><th>Call Vol</th><th>Strike</th><th>Put LTP</th><th>Put OI</th><th>Put Vol</th></tr></thead><tbody>{chain.data.rows.map((r:any)=><tr className={r.atm?"atm":""} key={r.strike}><td>{r.ce?.ltp??"—"}</td><td>{r.ce?.oi??"—"}</td><td>{r.ce?.volume??"—"}</td><td><b>{r.strike}</b></td><td>{r.pe?.ltp??"—"}</td><td>{r.pe?.oi??"—"}</td><td>{r.pe?.volume??"—"}</td></tr>)}</tbody></table></div></>}</section>;
 if(tab==="Backtesting") page=<section className="panel"><div className="page-heading"><div><p className="eyebrow">RESEARCH</p><h3>Multi-contract backtest</h3><p className="muted">Run ATM or several option contracts in one historical test.</p></div>{selector}</div>{!connected?<p className="error">Connect Kite first.</p>:<form className="backtest-form" onSubmit={backtest}><label>From<input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} required/></label><label>To<input type="date" value={toDate} onChange={e=>setToDate(e.target.value)} required/></label><label>Selection<select value={mode} onChange={e=>{setMode(e.target.value);setSelected([])}}><option value="ATM">ATM — CE + PE</option><option value="MANUAL">Multiple contracts</option></select></label>{mode==="ATM"&&<div className="atm-selection-card"><div><span className="live-label"><i/> AUTOMATIC STRIKE SELECTION</span><strong>ATM Call + Put</strong><p>Both CE and PE at the same nearest ATM strike will be tested.</p></div><span className="atm-chip">CE + PE</span></div>}{mode==="MANUAL"&&<div className="contract-picker"><span>Contracts — {selected.length} selected</span><div className="contract-grid">{(contracts.data??[]).slice(0,200).map((c:any)=><label className="contract-option" key={c.instrument_token}><input type="checkbox" checked={selected.includes(String(c.instrument_token))} onChange={e=>setSelected(x=>e.target.checked?[...x,String(c.instrument_token)]:x.filter(y=>y!==String(c.instrument_token)))} /><span>{c.tradingsymbol}</span><small>{c.expiry} · {c.strike} · {c.option_type}</small></label>)}</div></div>}<button disabled={mode==="MANUAL"&&!selected.length}>Run backtest</button></form>}{error&&<p className="error">{error}</p>}{result&&<>{result.results?<div className="comparison-grid">{result.results.map((r:any)=><div className="card" key={r.contract.tradingsymbol}><small>{r.contract.tradingsymbol}</small><strong>₹{r.summary.net_pnl}</strong><span>{r.summary.win_rate}% win rate · {r.summary.trades} trades</span></div>)}</div>:<section className="cards result-cards">{Object.entries(result.summary??{}).slice(0,8).map(([k,v])=><div className="card" key={k}><small>{k.replaceAll("_"," ")}</small><strong>{String(v??"—")}</strong></div>)}</section>}<h3>Executed trades</h3><Table rows={result.trades??[]} /></>}</section>;
 if(tab==="Broker") page=<section className="panel"><p className="eyebrow">BROKER</p><h3>Zerodha Kite</h3><div className="broker-card"><span className={`connection ${connected?"connected":"disconnected"}`}><i/> {broker.data?.status??"CHECKING"}</span><p className="muted">Redirect: backend callback → this frontend workspace.</p><button onClick={connect}>Connect Zerodha</button></div></section>;
 if(tab==="Strategies") page=<section className="panel"><h3>Strategies</h3><Table rows={strategies.data??[]} /></section>;
 if(["Orders","Positions","Trades"].includes(tab)) page=<section className="panel"><h3>{tab}</h3><Table rows={tab==="Orders"?orders.data:tab==="Positions"?positions.data:trades.data} /></section>;
 return <div className="app"><aside><div className="brand"><span className="brand-mark">◈</span><h1>AUTO BOT</h1></div><p className="mode-label">PAPER WORKSPACE</p>{tabs.map(x=><button className={`nav ${tab===x?"active":""}`} onClick={()=>setTab(x)} key={x}>{x}</button>)}</aside><main><header><div><p className="eyebrow">TRADING TERMINAL</p><h2>{tab}</h2><span className="paper">PAPER MODE</span></div><div className="header-actions"><span className={`connection ${connected?"connected":"disconnected"}`}><i/> Kite {broker.data?.status??"CHECKING"}</span><button className="secondary" onClick={logout}>Log out</button></div></header>{page}</main></div>;
}
